#custom archetypes
!setname 0xb02 Digi-Egg
!setname 0xb19 X-Antibody
!setname 0xd74 Digi-Humano
!setname 0xdf7 Digimon/Mon
!setname 0xdf8 Digi-Lendario
!setname 0xf0f Digi-escolhido
!setname 0x3763 Digivice
!setname 0x3764 Musica_tema/Digimon
!setname 0x3765 Tamers_Action_Card